# Generated by Django 3.2.16 on 2022-11-05 09:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='graphData',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='twitterZip',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='company',
            name='websiteData',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
