# Generated by Django 3.2.16 on 2022-11-05 16:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221105_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='api',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='graphData',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitterZip',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='variables',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='websiteData',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
