# Generated by Django 3.2.16 on 2023-01-28 19:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='newsArticles',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
